name = "zend-worker"
main = "src-ts/index.ts"
compatibility_date = "2023-04-18"

[build]
command = "worker-build --release"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room"},
  { name = "PEER", class_name = "Peer"},
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room", "Peer"]